export enum Events {
  USER_CREATED = 'USER_CREATED',
  ITEM_CREATED = 'ITEM_CREATED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  ITEM_DELETED = 'ITEM_DELETED',
  INVENTORY_CREATED = 'INVENTORY_CREATED',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  INVENTORY_DELETED = 'INVENTORY_DELETED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_DELETED = 'ORDER_DELETED',
}
