{
 "title": "OpenCost",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Monthly Cost of Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_total_hourly_cost) * 730",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(node_cpu_hourly_cost) * 730",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(node_ram_hourly_cost) * 730",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Memory Usage Per Namespace",
   "type": "timeseries",
   "description": "Measured in bytes of RAM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_allocation_bytes) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cost Per Namespace ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_cpu_allocation * 60 * on (node) group_left node_cpu_hourly_cost) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Cost Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_allocation_bytes * 60 * on (node) group_left node_ram_hourly_cost) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_cpu_allocation) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Cost of Persistent Volumes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pv_hourly_cost) by (persistentvolume) * 24 * 100",
     "legendFormat": "{{persistentvolume}}"
    }
   ]
  },
  {
   "title": "Hourly Cost Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "node_total_hourly_cost", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Hourly Cost of Load Balancers By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(kubecost_load_balancer_cost) by (namespace)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster Management Costs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubecost_cluster_management_cost) * 24",
     "legendFormat": "Daily"
    },
    {
     "expr": "sum(kubecost_cluster_management_cost) * 730",
     "legendFormat": "Monthly"
    }
   ]
  }
 ]
}